In [11]:
%load_ext kedro.extras.extensions.ipython
%reload_kedro

%load_ext autoreload
%autoreload 2

The kedro.extras.extensions.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.extras.extensions.ipython
2022-04-24 19:05:15,445 - root - INFO - No path argument was provided. Using: /Users/inigo/Programming/kedro-projects/kaggle-house-prices
2022-04-24 19:05:15,619 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2022-04-24 19:05:15,865 - root - INFO - ** Kedro project Kaggle House Prices
2022-04-24 19:05:15,867 - root - INFO - Defined global variable `context`, `session`, `catalog` and `pipelines`
2022-04-24 19:05:15,881 - root - INFO - Registered line magic `run_viz`
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:

os.environ["KAGGLE_username"] = "inigohrey"
os.environ["KAGGLE_key"] = "4da08432f758ed693cd24af8de591bd1"

from kaggle.api.kaggle_api_extended import KaggleApi
import pandas as pd

In [6]:
from kaggle_house_prices.utils.utils import set_cwd

In [7]:

api = KaggleApi()
api.authenticate()

In [8]:
api.competition_list_files("house-prices-advanced-regression-techniques")

[sample_submission.csv, test.csv, train.csv, data_description.txt]

sample_submission.csv

In [11]:
!pwd

/Users/inigo/Programming/kedro-projects/kaggle-house-prices/notebooks

In [9]:
target_path = Path("../data/01_raw/")

In [8]:
!pwd

/Users/inigo/Programming/kedro-projects/kaggle-house-prices/notebooks

In [12]:
catalog.list()

['house_prices', 'intermediate_house_prices', 'parameters']

In [25]:
import logging
log = logging.getLogger()

In [38]:
def load_kaggle_dataset(dataset, competition=None):
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        log.debug(str(temp_path))
        log.debug("ee")
        with set_cwd(temp_dir):
            _log_msg = f"Downloading dataset {dataset}"
            if competition is not None:
                _log_msg += f" from competition {competition}"
            log.info(_log_msg)
            api.competition_download_file(competition, dataset, quiet=True)
        df=pd.read_csv(temp_path/"train.csv")
    
    return df

#catalog.save("house_prices", df)

In [39]:
log.setLevel(logging.INFO)

In [40]:
house_prices = load_kaggle_dataset('train.csv', competition='house-prices-advanced-regression-techniques')

2022-04-24 11:31:08,665 - root - INFO - Downloading dataset train.csv from competition house-prices-advanced-regression-techniques

In [22]:
with tempfile.TemporaryDirectory() as temp_dir:
    temp_path = Path(temp_dir)
    with set_cwd(temp_dir):
        log.info("Downloading {'train.csv'}")
        api.competition_download_file('house-prices-advanced-regression-techniques','train.csv', quiet=True)
    df=pd.read_csv(temp_path/"train.csv")

catalog.save("house_prices", df)

2022-04-24 11:11:06,227 - kedro.io.data_catalog - INFO - Saving data to `house_prices` (CSVDataSet)...

In [6]:
with tempfile.TemporaryDirectory() as temp_dir:
    temp_path = Path(temp_dir)
    api.competition_download_file('house-prices-advanced-regression-techniques','train.csv', path=temp_path)
    df=pd.read_csv(temp_path/"train.csv")
    df.to_csv(target_path/"house_prices_train.csv", index=False)

NameError: name 'api' is not defined

In [20]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [46]:
api.competition_download_files('house-prices-advanced-regression-techniques')
print("hello")

hello

In [14]:
from kaggle_house_prices.api import kaggle

In [15]:
dataset = kaggle.KaggleDataSet(credentials={"user": "inigohrey", "key": "4da08432f758ed693cd24af8de591bd1"})

In [18]:
dataset.load_competition_dataset('house-prices-advanced-regression-techniques', 'train.csv', index_col="Id")

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [21]:
dataset._download_single_competition_file('house-prices-advanced-regression-techniques', "data_description.txt", "../docs/reference")

PosixPath('../docs/reference/data_description.txt')

In [23]:
os.environ["KAGGLE_user"]

'inigohrey'